const VBT2 =
    [
        "Paradevi, whose nature is visarga, or creation, manifests as the upward prana and the downward apana. By fixing the mind at the two points of generation (of prana and apana), the state of fullness results.",
        "When the ingoing pranic air and outgoing pranic air are both restrained in their space from their (respective points of) return, the essence of bhairava, which is not different from bhairavi, manifests.",
        "When Shakti in the form of vayu or pranic air is still and does not move swiftly in a specific direction, there develops in the middle, through the state of Nirvikalpa, the form of Bhairava.",
        "When Kumbhaka takes place after Puraka or Rechaka, then the shakti known as shanta is experienced and through that peace (the bhairava consciousness) is revealed.",
        "Concentrate on the shakti arising from the root like the rays of the sun, gradually becoming subtler and subtler, until at last she dissolves in the dwadashanta and bhairava manifests.",
        "(Meditate on that shakti) moving upwards like lightning through all the chakras one by one to the dwadashanta. Then at last the glorious form of Bhairava dawns.",

        "The twelve (centres) should be pierced successively through proper understanding of their (associated) twelve letters. Thus becoming liberated from the gross then the subtle, one by one, at the end (of its journey) the kundalini becomes Shiva.<br>Then, having filled the tip of moordha (forehead) and crossed the bridge between the eyebrows, the mind rises above all dichotomizing thought patterns and omnipresence (prevails).",

        "Like the live different coloured circles on the peacock's feathers, one should meditate on the five voids. Then by following them to the end, which becomes the principle void, enter the heart.<br>In this way, wherever there is mindful awareness, either on the void, or on another (object such as a) wall, or on an excellent person (such as guru), gradually the boon of absorption into the self is granted.",

        "Having closed the eyes, and fixing the attention at the crown of the head, gradually stabilize the mind and direct it towards the goal, which will become discernible.",
        "One should meditate on the inner space of the medial nadi (sushumna) situated in the central axis of the body (the spinal column), which is as slender as a fibre of the lotus stem, and then by the grace of Devi, the divine (form) is revealed.",
        "By using the hands (as tools) to block the entrances in all directions, the eyebrow centre is pierced and bindu (or light) is seen. Being gradually absorbed within that, the supreme state is realized.",
        "Whenever one meditates upon the subtle lire, in the form of a tilak (like the mark on the forehead), or on the bindu at the end of the shikha, a condition of agitation and shaking is produced, followed by absorption and dissolution in the cave of the heart.",
        "One, who is adept in listening to the unstruck sound in anahata, (which is) uninterrupted like a rushing river, attains the supreme state of Brahma by mastery of shabdabrahman, the form of Brahman as sound.",
        "O Bhairavi, one who repeats the Pranava (Aum) perfectly, while concentrating on the void for protracted periods, experiences the void, and by that void the transcendental shakti (is revealed).",
        "Whoever contemplates even on the matras or letters (of Aum) from first to last, in the form of void, verily that sadhaka by meditation on the void becomes the void.",
        "When one-pointed awareness on the prolonged inner sounds of different musical instruments, such as stringed, wind and percussion, is gradually established, in the end the body becomes the supreme space.",
        "By repetition of all the gross letters of the bija mantras successively, including the 'M', (and meditating thus! on the void within each sound, one verily becomes Shiva.",
        "All the directions should be contemplated upon simultaneously in one's own body as space or void. The mind (too) being free from all thoughts becomes dissolved (in the vacuous space of consciousness).",
        "One who contemplates simultaneously on the void of the back (spinal column) and the void of the root becomes void-minded (completely free of all thought constructs or Vikalpas) by that energy which is independent of the body.",
        "By steady contemplation on the void of the back (sushumna), the void of the root and the void of the heart simultaneously, there arises the state of nirvikalpa, which is free from thought constructs.",
        "If one concentrates on the body as a void, even for a moment, with the mind free from thought, then one attains thoughtlessness and verily becomes that form of void (known as Bhairava).",
        "O gazelle-eyed one, concentrate upon all the constituents of the body pervaded by space, so that the thought becomes steady.",
        "One should contemplate on the skin of the body as a mere wall or partition with nothing inside it. By meditating thus, he becomes like the void, which cannot be meditated upon.",
        "O embodiment of good fortune, one who contemplates with closed eyes and one-pointed concentration on the mantra in the middle of the lotus in the heart space achieves the highest spiritual realization.",
        "When the mind is dissolved in dwadashanta by steady awareness and steady practice, the true nature or essence of the goal manifests everywhere in one's body.",
        "By bringing the mind forcibly to dwadashanta again and again, however and wherever possible, the fluctuations of the mind diminish day by day, so that each moment becomes an extraordinary state.",
        "One should contemplate that one's own body has been burnt by Kaalagni, arising, from the movement of time. Then at last one will experience tranquility.",
        "In the same way, having meditated with an unwavering and one-pointed mind on the entire universe being burnt (by Kaalagni), that man becomes a godman or attains a supreme state of manhood.",
        "Dharana on those constituents which comprise one's own body and the whole universe, such as the tattwas and tanmatras, from subtle to subtlest, leads to the source of existence. (In this way) Paradevi, the supreme goddess, (is revealed) at the end of meditation.",
        "Having meditated on the gross and weak shakti in the twelve Indriyas (thus making it subtle), one who enters the heart space and meditates there attains mukti and becomes liberated.",
        "By meditating on the entire form of the universe and the course of its development through time and space, gradually dissolve the gross into the subtle and the subtle into the state of being beyond, until the mind is finally dissolved (into pure consciousness).",
        "By this method one should meditate on all the sides or aspects of the universe up to the Shiva tatwa (which is the quintessence) of all. In this way the experience of the supreme reality arises.",
        "O great Goddess, one should concentrate on this universe as nothing but void. Dissolving the mind also like this, one then experiences the state of laya, or total dissolution.",
        "One should fix his sight (on the empty space) inside the pot, leaving aside the enclosing structure. Thus, the pot bei ng gone, the mind will at once be dissolved (into the space). Through that laya the mind becomes completely absorbed (in the void).",
        "One should fix his gaze on a treeless place, like bare mountains or rocks, where there is no support for the mind to dwell on. Then the modifications of the mind become less and the experience of dissolution takes place.",
        "One should think of two objects, and in the event of such knowledge being matured, then cast both aside and dwell (on the gap or space) in the middle. Having meditated in the middle, the experience of the essence arises.",
        "When the mind is restrained to one object of awareness, casting all others aside and not allowing movement to lake place from one to another, then inside that perception the awareness blossoms.",
        "One should concentrate with an unwavering mind on all existence, the body and even the universe simultaneously as nothing but consciousness, then the supreme conscious- ness arises.",
        "From the fusion of both vayus (prana and apana) inside or outside(the body), the yogi attains equilibrium and becomes fit for the proper manifestation of consciousness.",
        "One should contemplate simultaneously on the entire universe or on one's own body filled with the bliss of the sell. I hen through one's own nectar, one becomes alive with the supreme bliss.",
        "O gazelle-eyed one, verily by applying the performance of religious austerities, great bliss arises immediately, by which the essence is illumined.",
        "By blocking all the channels (of perception) the prana- shakti moves slowly upwards (through the spinal column). At that time, feeling the sensation of an ant crawling in the body, one experiences the supreme bliss.",
        "One should throw the blissful mind into the fire (manipura chakra) in the middle of that fibre-like lotus stalk (sushumna) or into that which is only full of air (anahata chakra). Then one is united with the remembrance of bliss.",
        "By the union with shakti there is excitation and in the end, one is absorbed into shakti. That bliss (of union) which is said to be the nature of Brahman (ever-expanding consciousness), that bliss is (in reality) one's own self.",
        "O Queen of Gods, the bliss of a woman is attained even in the absence of shakti. By fully remembering and absorbing the mind in the experience of kissing, hugging and embracing, the bliss swells.",
        "When great joy is obtained (through any event such as) meeting with relatives, one should meditate on that with one-pointedness, until the mind becomes absorbed and the bliss ever arises.",
        "If one concentrates on eating and drinking and the happiness obtained by that joy of taste, from such contemplation of enjoyment arises the state of fullness, which then becomes supreme joy or bliss.",
        "As a result of concentration on the pleasures of the senses, such as music or song, the yogis experience equal happiness (or pleasure) within. By being (thus) absorbed the yogi ascends beyond the mind and becomes one with that (supreme).",
        "Whenever there is satisfaction of mind and the mind is held there alone, the nature of supreme bliss manifests.",
        "By entering that state preceding sleep, where the awareness of the outer world has faded, (the mind is absorbed in the threshold state) which the supreme goddess illumines.",
        "By gazing on the space that appears variegated by the rays of the sun or an oil lamp, there the nature of one's essential self is illumined.",
        "At the time of intuitive perception (the attitudes of) karankini, krodhana, bhairavi, lelihanaya and khechari are revealed, whereby the supreme attainment manifests.",
        "Seated on a soft seat, by means of one buttock, with the hands and legs relaxed, at this time the mind becomes full of transcendence.",
        "Sitting in a correct posture and curving the arms and hands into a circle, fix the gaze inside this space. The mind becomes peaceful by this laya.",
        "One should steady the gaze (without blinking) on the gross form of any object. When the mind is transfixed and made supportless (without any other thought or feeling), it at once acquires the state of shiva (transcendence).",
        "(Placing) the middle of the tongue in that which has been opened widely and throwing the consciousness in the middle, mentally repeating 'Ha', the mind will be dissolved in tranquility.",
        "While sitting or lying down, one should think of one's own body as being supportless (suspended in space). Then, in a moment (the samskaras or thought constructs) of the mind being reduced, it ceases to be a reservoir (of old mental dispositions).",
        "O Goddess, as a result of slowly swinging or rocking the body, one attains a tranquil state of mind and floats into the stream of divine consciousness.",
        "O Devi, having fixed the gaze continuously on the clear sky (without blinking) and with a steady awareness, at once the nature of Bhairava is achieved.",
        "One should contemplate on the sky as the form of bhairava (until it is) all absorbed in the forehead. Then all that (space) will be entered by the essence of light in the state of bhairava.",
        "Knowing a bit about duality, the outer light and darkness in the manifest world and so on, one who again experiences the infinite form of Bhairava procures illumination.",
        
        "Like this, one should ever contemplate on the terrible darkness of night during the dark fortnight of the moon, if he desires to attain the form of bhairava.< br > Similarly, while closing the eyes, one should contemplate on the profound darkness spreading in front as the form of bhairava.Thus he becomes one with that.",

        "Whoever restrains even the same sense organ enters the one void without a second by this obstruction and there the atma, or self, is illumined.",
        "O Devi, by recitation of akaara, the letter 'A', in the absence of bindu and visarga, a great torrent of knowledge of the supreme Lord, Parameshvara, at once arises.",
        "When the mind is joined with the visarga, at the end of the visarga it is made supportless. In this way the mind is touched by the eternal Brahma, or the supreme consciousness.",
        "When one meditates on one's own self in the form of unlimited space (in all) directions, the mind is suspended and shakti in the form of consciousness is revealed as the form of one's own self.",
        "At first one should pierce any limb of the body a little bit with a sharp, pointed needle or any other instrument. Then projecting the consciousness there, verily there is movement towards the pure nature of bhairava.",
        "By contemplating thus, the antahkarana, or inner instrument of mind, and so on is non-existent within me, then, in the absence of vikalpas (thought constructs), one becomes free from the vikalpas.",
        "Maya is the delusive principle residing (in manifest existence), causing name and limited activity. Considering thus the nature or functions of the various elements, one (realizes that he) is not separate (from the supreme reality).",
        "Observing the desires, which spring up in a flash, put an end to them.Then verily(the mind) will be absorbed in the very source from which they have arisen.",
        "(One should contemplate thus:) when my desires do not produce knowledge, then what am I? Indeed being absorbed in the essence I am, and identifying with that, one becomes that.",
        "When desire or knowledge arises, one should fix the mind there, thinking that to be the very self. Making the mind absolutely one-pointed (in this way), he realizes the essence of the tattwas.",
        "O dear one, (compared to absolute knowledge, all relative) knowledge is without cause, and thus becomes baseless and deceptive. In reality, knowledge does not belong to any one person. Contemplating like this, one becomes Shiva.",
        "He (Bhairava) is of the nature of undifferentiated consciousness in all embodied forms. Therefore, those persons who contemplate on all creation pervaded by that consciousness, transcend relative existence.",
        "When lust, anger, greed, delusion, arrogance and jealousy are seen (within), having fixed the mind completely (on these), the underlying tattwa, or essence, alone remains.",
        "Meditating on the manifest world as imagined or illusive, like a magic show or a painting, and seeing all existence as transient, happiness arises.",
        "O Goddess, the mind should not dwell on pain or pleasure, but the essence that remains in the middle (in between the opposites) should be known.",
        "Abandoning consideration for one's own body, one should contemplate with a firm mind that, 'I am everywhere'. When this is seen (by means of concentrated insight) one does not see another and thus becomes happy.",
        "Contemplating on that special knowledge, for example, the analogy of the jar, or that the desires, etc. exist not only within me but everywhere, one thus becomes all-pervasive.",
        "The subject-object consciousness is common to everybody. Yogis, however, are especially alert regarding this relationship.",
        "Contemplate on consciousness, such as one's own and even in another's body as well. Thus abandoning all physical expectation, one becomes all-pervasive in the course of time.",
        "O gazelle-eyed one, having free the mind of all supports, one should refrain from all the Vikalpas (thoughts/counter- thoughts). Then, the self becomes one with the supreme Sell in the state of bhairava.",
        "The supreme Lord, who is omnipresent, omniscient and omnipotent, verily, I am lie and 1 have the same shiva- nature. (Contemplating thus with firm conviction, one becomes Shiva.",
        "Just as waves arise from water, (lames from lire and light rays from the sun, similarly die waves of bhairava, which produce die different emanations of die universe, are verily my source.",
        "Whirling the body round and round until it falls on the ground makes the energy causing commotion at once (become static). By dial cessation the supreme slate appears.",
        "Being powerless to perceive objects due to ignorance or wrong perception, if one is able to dissolve the mind by absorbing it on the erroneous perception of objects, then at the end of commotion brought about by that absorption, there the form of Bhairava appears.",
        "Listen, O Devi, as I am telling you about this (mystic) tradition in its entirety. If the eyes are fixed in a steady gaze (without blinking), kaivalya will arise immediately.",
        "Contracting (or closing) the openings of the ears and also the lower opening (reproductive/excretory organs) in the same way, and then meditating on the palace of the anahad (unstruck) sound within, one enters die eternal Brahma.",
        "Standing above a deep hole or well and looking steadily downward (into the abyss), the mind becomes entirely free of vikalpas and dissolution immediately manifests.",
        "Wherever the mind moves, whether outwards or inwards, there the all-pervasive slate of shiva will go.",
        "Wherever the consciousness leads through the channel of the eyes, by contemplation on that object alone being of the same nature as that of the supreme, absorption of mind and the state of poornatva are experienced.",
        "At the beginning and end of sneezing, in terror, sorrow or confusion, when fleeing from a battlefield, during (keen) curiosity, or at the onset or appeasement of hunger, that state is the external existence of Brahma.",
        "Leave the mind aside when memorable objects of die past, such as one's country or land arise, making one's body supportless; then the omnipresent and mighty Lord manifests.",
        "O Goddess, momentarily casting the gaze on some object and slowly withdrawing it with the knowledge and impression of that object, one becomes the abode of the void.",
        "That, intuition which emerges from the intense devotion of one who is perfectly detached is known as the Shakti of Shankara. By contemplating regularly on that (shakti), Shiva (is revealed) there.",
        "When one perceives a particular object, vacuity is established regarding all other objects. (Contemplating on that (vacuity) verily, even though the particular object is still known or perceived, the mind rests in tranquility.",
        "What people of little understanding believe to be purity is neither pure nor impure to one who has experienced shiva. Nirvikalpa, or freedom from vikalpas, is the real purification by which one attains happiness.",
        "The reality of bhairava dwells everywhere, even in ordinary people. By contemplating thus, \"There is nothing other than Him,\" one attains the non-dual state (of homogenous awareness).",
        "One who makes no distinction between friend and foe, honour and dishonour, knowing Brahman to be full in itself (all pervading), becomes supremely happy.",
        "One should never think in terms of friendship or enmity. Being free from (this idea) of friend and foe, in between the brahma bhava, or nature of supreme consciousness, blooms.",
        "By contemplating on bhairava as all that which is void and cannot be known, grasped or imagined, at the end realization takes place.",
        "Fixing the mind in the outer space, which is eternal, without support, void, omnipresent and beyond estimation or calculation, one enters into the formless, unmanifest dimension.",
        "Wherever the mind dwells, casting that aside that very moment, the mind becomes supportless and free from disturbance.",
        "The word Bhairava denotes he who dispels all fear and terror, who howls and cries, who gives all, and who pervades the entire universe (manifest and unmanifest). He who constantly repeats the word bhairava becomes one with Shiva.",
        "At the time of asserting, \"1 am, \" \"This is mine, \" and so on, by inspired meditation on Fat (that highest reality), the mind becomes supportless.",
        "Meditating every moment on the words: eternal, omnipresent, supportless, all-pervasive, master of the universe, one attains fulfilment in accordance with their meaning.",
        "This world is (illusory) like magic, devoid of any essence. What essence exists in magic? Being firmly convinced of this, one attains peace.",
        "How can there be knowledge or activity of the changeless atman, or self? All external objects are under the control of knowledge. Therefore, this world is void.",
        "There is neither bondage nor liberation for me. These scare cowards and are the reflections (projections) of the intellect, just as the sun is reflected in water.",
        "All the doors of perception produce pain and pleasure through contact with the senses. Thus, casting aside (the sensory objects) and withdrawing (the senses) within, one abides in one's own self.",
        "Knowledge reveals all and the self of all is the revealer (knower). One should contemplate on the knowledge and the knower as being one and the same.",
        "O dear one, when the mind, awareness, energy and individual self, this set of four dissolves, then the state of bhairava manifests."

    ]